config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users, controllers: { registrations: 'registrations' }
	root "dashboard#index"

	get 'dashboard/search', to: "dashboard#search", as: :search_dashboard

	resources :users do
		resources :exercises
	end

	resources :friendships, only: [:show, :create, :destroy]

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user
	validates :user_id, presence: true
	validates :duration_in_min, presence: true, numericality: {only_integer: true}
	validates :workout, presence: true
	validates :workout_date, presence: true
	validate :workout_date_is_valid_date

	def workout_date_is_valid_date
		if not workout_date.is_a?(Date)
			errors.add(:workout_date, "Must be a valid date format")
		end
	end

	default_scope { where("workout_date > ?", 7.days.ago).order(workout_date: :desc) }
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"

	def self.get_friendship_id(current_user, friend)
		find_by(user_id: current_user.id, friend_id: friend.id).id
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :exercises, dependent: :destroy
	validates :last_name, presence: true
	has_many :friendships, dependent: :destroy
	has_many :friends, through: :friendships, class_name: "User", dependent: :destroy
	self.per_page = 10

	def full_name
		"#{first_name if !first_name.nil?} #{last_name}".strip
	end

	def self.search_by_name(name)
		names_arr = name.split(" ")
		if names_arr.size == 1
			self.where("first_name LIKE :name1 or last_name LIKE :name2", 
								 name1: "%#{names_arr[0]}%", name2: "%#{names_arr[0]}%").order(:first_name)
		else
			self.where("first_name Like :name1 or first_name Like :name2 or last_name Like :name1 or last_name Like :name2", name1: "%#{names_arr[0]}%", name2: "%#{names_arr[1]}%").order(:first_name)
		end
	end

	def follows_or_same?(new_friend)
		self.friends.include?(new_friend) or self == new_friend
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
	def index
		@athletes = User.paginate(page: params[:page])
	end

	def search
		if not params[:search_name].empty?
			@athletes = User.search_by_name(params[:search_name]).paginate(page: params[:page], per_page: 5)
		else
			redirect_to root_path
			flash[:danger] = "Please enter a valid search term"
		end
	end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_exercise, except: [:index, :new, :create]

	def index
		@exercises = current_user.exercises.all
		@friends = current_user.friends
	end

	def new
		@exercise = current_user.exercises.new
	end

	def create
		@exercise = current_user.exercises.build(exercise_params)	
		respond_to do |format|
			if @exercise.save
				format.html {redirect_to [current_user, @exercise], flash: { success: "Exercise has been created" } }
			else
				format.html {render :new}
				flash[:danger] = "Exercise has not been created"
			end
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			if @exercise.update(exercise_params)
				format.html {redirect_to [current_user, @exercise], flash: {success: "Exercise has been updated"}}
			else
				format.html {render :edit, flash: {danger: "Exercise has not been updated"}}
			end
		end
	end

	def show
	end

	def destroy
		@exercise.destroy
		flash[:success] = "Exercise has been deleted"
		redirect_to user_exercises_path(current_user)
	end

	private
	def exercise_params
		params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
	end

	def set_exercise
		@exercise = Exercise.find(params[:id])
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		friend = User.find(params[:friend_id])
		if not current_user.follows_or_same?(friend)
			Friendship.create(friendship_params.merge!(user_id: current_user.id))
			redirect_to root_path
			flash[:success] = "You are now following #{friend.full_name}"
		end
	end

	def show
		@friend = User.find(params[:id])
		if current_user.friends.include?(@friend)
			@friend_exer = @friend.exercises.all
		else
			if current_user == @friend
				redirect_to user_exercises_path(current_user)
			else 
				redirect_to :back
				flash[:danger] = "You must follow #{@friend.full_name} before that action"
			end
		end
	end

	def destroy
		@friendship = Friendship.find(params[:id])
		@friendship.destroy
		flash[:success] = "#{@friendship.friend.full_name} unfollowed"
		redirect_to user_exercises_path(current_user)
	end

	private
	def friendship_params
		params.permit(:friend_id)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private
	def sign_up_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def devise_error_messages!
		return "" if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
		html = <<-HTML
		<div class="alert alert-dismissible alert-error alert-danger" role="alert">
			<a href="#", class="close", data-dismiss="alert">&times;</a>
			<%= content_tag :div, msg if msg.is_a?(String) %>
		</div>
		HTML
		html.html_safe
	end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/dashboard/index.html.erb
<div class="jumbotron cover-pic">
	<h1 class="text-center">Workout Lounge</h1>
	<p class="text-center">Share your workouts with your friends and family.</p>
</div>

<h3 class="">
	<span class="label label-danger">
		Note: Sign in for testing purposes: [Email: "warren@example.com", Password: "password"]
	</span>
</h3>
<div class="row">
	<div class="col-md-10">
		<h2>List of Members</h2>
		<%= will_paginate @athletes, renderer: BootstrapPagination::Rails, class: "pull-left paginate" %>
	</div>
</div>

<div class="row">
	<% @athletes.each do |athlete| %>
		<div class="col-md-10">
			<div class="well member vcenter">
				<%= athlete.full_name %>
				<% if user_signed_in? %>
					<%= link_to "Follow", friendships_path(friend_id: athlete.id), 
												method: :post, 
											  class: "btn btn-primary pull-right" unless current_user.follows_or_same?(athlete) %>	
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/dashboard/search.html.erb
<div class="row search-result">
	<% @athletes.each do |athlete| %>
		<div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
			<div class="well member">
				<%= athlete.full_name %>
				<% if user_signed_in? %>
					<%= link_to "Follow", friendships_path(friend_id: athlete.id), 
												method: :post, 
											  class: "btn btn-primary pull-right vcenter" unless current_user.follows_or_same?(athlete) %>	
				<% end %>

			</div>
		</div>
	<% end %>
</div>

<div class="text-center">
	<%= will_paginate @athletes, renderer: BootstrapPagination::Rails %>
</div>

app/views/exercises/_form.html.erb
<div class="row">
	<div class="col-md-12 col-sm-12">
		<%= form_for [current_user, @exercise], html: {class: "form-horizontal", role: "form"} do |f| %>
			<% if @exercise.errors.any? %>	
				<div id="error_explanation">
					<h2><%= pluralize(@exercise.errors.count, "error") %>
					prohibited this exercise from being saved.</h2>
					<ul>
						<% @exercise.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			
			<div class="form-group">
				<div class="control-label col-md-2 col-sm-2">
					<%= f.label :duration_in_min, "Duration (min)" %>
				</div>
				<div class="col-md-10 col-sm-10">
					<%= f.number_field :duration_in_min, class: "form-control" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-md-2 col-sm-2">
					<%= f.label :workout, "Workout Details" %>
				</div>
				<div class="col-md-10 col-sm-10">
					<%= f.text_area :workout, class: "form-control", rows: "10" %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-md-2 col-sm-2">
					<%= f.label :workout_date, "Activity Date" %>
				</div>
				<div class="col-md-10 col-sm-10">
					<%= f.text_field :workout_date, class: "form-control" %>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10 col-sm-10">
					<%= f.submit class: "btn btn-primary btn-lg" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/exercises/edit.html.erb
<h1 class="text-center">Editing Exercise for <%= current_user.full_name %></h1>

<%= render "form" %>

<div class="row">
	<div class="col-md-10 col-sm-10 col-md-offset-2 col-sm-offset-2">
		<%= link_to "Show", [current_user, @exercise], class: "btn btn-md btn-info" %>
		<%= link_to "Back", user_exercises_path(current_user), class: "btn btn-md btn-warning" %>
	</div>
</div>

app/views/exercises/index.html.erb
<div class="col-md-8 col-sm-8 col-xs-12">
	<% unless @exercises.empty? %>
		<h1>Listing Exercises</h1>

		<table class="table table-striped">
			<thead>
				<tr>
					<th>Duration (min)</th>
					<th>Workout Details</th>
					<th>Activity Date</th>
					<th colspan="3"></th>
				</tr>
			</thead>
			<tbody>
				<% @exercises.each do |exercise| %>
					<tr>
						<td><%= exercise.duration_in_min %></td>
						<td><%= truncate(exercise.workout, length: 100) %></td>
						<td><%= exercise.workout_date %></td>
						<td><%= link_to "Show", user_exercise_path(current_user, exercise), 
																		class: "btn btn-xs btn-primary" %></td>
						<td><%= link_to "Edit", edit_user_exercise_path(current_user, exercise), 
																		class: "btn btn-xs btn-success" %></td>
						<td><%= link_to "Delete", [current_user, exercise], 
																			method: :delete, 
																			data: {confirm: "Are you sure?"},
																		  class: "btn btn-xs btn-danger"	%></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<br>
	<% else %>
		<div class="alert alert-danger message-font text-center" role="alert">
			No workouts yet.
		</div>
		<br>
	<% end %>
	<%= link_to "New Workout", new_user_exercise_path(current_user), class: "btn btn-primary link" %>
	<p></p><br>
	<%= content_tag :div, "", id: "chart", data: {workouts: @exercises} %>
</div>

<div class="col-md-4 col-sm-4 col-xs-12">
	<h1 class="text-center">My Friends</h1>
	<% @friends.each do |friend| %>
		<div class="col-md-offset-3 col-md-6 friend_name">
			<%= link_to friend.full_name, friendship_path(friend) %>
		</div>
		<div class="col-md-3">
			<%= link_to "Unfollow", friendship_path(Friendship.get_friendship_id(current_user, friend)), 
															method: :delete, 
															data: {confirm: "Are you sure?"}, 
															class: "btn btn-danger btn-sm" %>
		</div>
	<% end %>
</div>

app/views/exercises/new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.full_name %></h1>

<%= render "form" %>

<div class="row">
	<div class="col-md-10 col-sm-10 col-md-offset-2 col-sm-offset-2">
		<%= link_to "Back", user_exercises_path(current_user), 
												class: "btn btn-warning link", id: "new-exer-btn" %>
		
	</div>
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
	<div>
		<h2 class="show-header">Showing <%= "#{@exercise.user.full_name}'s Workout Details" %></h2>
	</div>
	<div class="col-xs-12 col-md-10 well member">
		<div class="col-xs-4">
			<strong>Duration (min):</strong>
		</div>
		<div class="col-xs-8 text-right">
			<%= @exercise.duration_in_min %>
		</div>
	</div>
	<div class="col-xs-12 col-md-10 well member">
		<div class="col-xs-4">
			<strong>Workout Details:</strong>
		</div>
		<div class="col-xs-8 text-right">
			<%= truncate(@exercise.workout, length: 50) %>
		</div>
	</div>
	<div class="col-xs-12 col-md-10 well member">
		<div class="col-xs-4">
			<strong>Activity Date:</strong>
		</div>
		<div class="col-xs-8 text-right">
			<%= @exercise.workout_date %>
		</div>
	</div>
	<br>
	<br>
	<div class="row">
		<div class="col-xs-12 col-md-10 member">
			<%= link_to "Back", user_exercises_path(current_user), class: "btn btn-warning btn-lg" %>
		</div>
	</div>
</div>

app/views/friendships/show.html.erb
<div class="col-md-8">
	<% unless @friend_exer.empty? %>
		<h1><%= @friend.full_name %>'s Exercises</h1>

		<table class="table table-striped">
			<thead>
				<tr>
					<th>Duration (min)</th>
					<th>Workout Details</th>
					<th>Activity Date</th>
						<th colspan="1"></th>
				</tr>
			</thead>
			<tbody>
				<% @friend_exer.each do |exercise| %>
					<tr>
						<td><%= exercise.duration_in_min %></td>
						<td><%= truncate(exercise.workout, length: 100) %></td>
						<td><%= exercise.workout_date %></td>
						<td><%= link_to "Show", user_exercise_path(@friend, exercise), 
																		class: "btn btn-xs btn-primary" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>

		<br>

		<%= content_tag :div, "", id: "chart", data: {workouts: @friend_exer} %>
		<br>
	<% else %>
		<div class="alert alert-danger message-font text-center" role="alert">
			<%= @friend.full_name %> has no workouts yet.
		</div>
	<% end %>
	<%= link_to "Back", user_exercises_path(current_user), class: "btn btn-primary" %>
</div>

<div class="col-md-4 col-sm-4 col-xs-12">
	<h1 class="text-center"><%= @friend.full_name %>'s Friends</h1>
	<% @friend.friends.each do |acq| %>
		<div class="col-md-offset-3 col-md-6 friend_name">
			<%= link_to acq.full_name, friendship_path(acq) %>
		</div>
		<div class="col-md-3">
			<% if not current_user.follows_or_same?(acq) %>
				<%= link_to "Follow", friendships_path(friend_id: acq.id), method: :post, class: "btn btn-primary btn-sm" %>
			<% else %>	
				<% if current_user == acq %>
					<span class="label label-info">That's me!</span>
				<% else %>
					<span class="label label-info">You are following</span>
				<% end %>	
			<% end %>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "shared/header" %>
	<%= render "shared/main" %>	
	<%= render "shared/footer" %>	
</body>
</html>

app/views/shared/_footer.html.erb
<div class="container-fluid">

	<div class="row">
		<div class="text-center">
			<footer role="contentinfo">
				<p><small>Copyright &copy; Workout Logs Company</small></p>
			</footer>
		</div>
	</div>

</div>

app/views/shared/_header.html.erb
<header role="banner">
	<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
					data-target="#bs-example-navbar-collapse-1">
					
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "Athletes Den", root_path, class: "navbar-brand" %>
			</div>
			<div id="bs-example-navbar-collapse-1" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="active">
						<%= link_to "Home", root_path %>
						<span class="sr-only">(current)</span>
					</li>
				</ul>
				<%= form_tag(search_dashboard_path, method: 'get', class: "navbar-form navbar-left", role: "search") do %>
					<div class="form-group">
						<%= text_field_tag "search_name", nil, placeholder:"Search for friends", class: "form-control" %>
					</div>
					<%= submit_tag "Search", class: "btn btn-default" %>
				<% end %>
				<ul class="nav navbar-nav navbar-right">
					<% if not user_signed_in? %>
						<li><%= link_to "Sign up", new_user_registration_path %></li>
						<li><%= link_to "Sign in", new_user_session_path %></li>
					<% else %>
						<li><%= link_to "My Lounge", user_exercises_path(current_user) %></li>
						<li class="navbar-text">Hello! <%= current_user.full_name %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
						<li><%= link_to "Edit Account", edit_user_registration_path(current_user) %></li>
						<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
</header>

app/views/shared/_main.html.erb
<div class="container">
	<% flash.each do |name, msg| %>
		<div class="alert alert-dismissible alert-<%= "#{name}" %>" role="alert">
			<a href="#" class="close" data-dismiss="alert" aria-label="Close">&times;</a>
			<%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
		</div>
	<% end %>
	<%= yield %>
</div>